In [28]:
import numpy as np
import pandas as pd
import sqlite3
import os

In [29]:
!pwd

/home/kodolamacz/DATA_SCIENCE/SagesDataScience_Zjazdy/04_PandasMatplotlib

In [30]:
import os

In [31]:
os.getcwd()

'/home/kodolamacz/DATA_SCIENCE/SagesDataScience_Zjazdy/04_PandasMatplotlib'

In [32]:
airlines = pd.read_csv("nycflights13_airlines.csv.gz", compression="gzip", comment="#")
airports = pd.read_csv("nycflights13_airports.csv.gz", compression="gzip", comment="#")
flights = pd.read_csv("nycflights13_flights.csv.gz", compression="gzip", comment="#")
planes = pd.read_csv("nycflights13_planes.csv.gz", compression="gzip", comment="#")
weather = pd.read_csv("nycflights13_weather.csv.gz", compression="gzip", comment="#")

In [33]:
airlines = pd.read_csv("nycflights13_airlines.csv.gz", comment="#")

In [34]:
airlines.head()

  carrier                    name
0      9E       Endeavor Air Inc.
1      AA  American Airlines Inc.
2      AS    Alaska Airlines Inc.
3      B6         JetBlue Airways
4      DL    Delta Air Lines Inc.

In [35]:
airports.head()

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York

In [36]:
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00

In [37]:
planes.head()

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan

In [38]:
weather.head()

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,0,37.04,21.92,53.97,230.0,10.35702,11.918651,0.0,1013.9,10.0,2013-01-01 01:00:00
1,EWR,2013,1,1,1,37.04,21.92,53.97,230.0,13.80936,15.891535,0.0,1013.0,10.0,2013-01-01 02:00:00
2,EWR,2013,1,1,2,37.94,21.92,52.09,230.0,12.65858,14.567241,0.0,1012.6,10.0,2013-01-01 03:00:00
3,EWR,2013,1,1,3,37.94,23.00,54.51,230.0,13.80936,15.891535,0.0,1012.7,10.0,2013-01-01 04:00:00
4,EWR,2013,1,1,4,37.94,24.08,57.04,240.0,14.96014,17.215830,0.0,1012.8,10.0,2013-01-01 05:00:00

In [39]:
# pd.read_csv("/home/kodolamacz/bootcamp-2018-07/Pandas/nycflights13_airlines.csv.gz", )
# pd.read_csv("/home/kodolamacz/Pobrane/nycflights13_airlines.csv.gz",)

In [40]:
os.getcwd()

'/home/kodolamacz/DATA_SCIENCE/SagesDataScience_Zjazdy/04_PandasMatplotlib'

In [41]:
os.path.join("folder1", "folder2")

'folder1/folder2'

In [42]:
db_name = 'nycflights13.db'
os.path.join(os.getcwd(), db_name)

'/home/kodolamacz/DATA_SCIENCE/SagesDataScience_Zjazdy/04_PandasMatplotlib/nycflights13.db'

In [43]:
db_name = 'nycflights13.db'
os.remove(os.path.join(os.getcwd(), db_name))

In [44]:
db_name = 'nycflights13.db'
con = sqlite3.connect(os.path.join(os.getcwd(), db_name))

planes.to_sql("planes", con, if_exists="replace")
airlines.to_sql("airlines", con, if_exists="replace")
flights.to_sql("flights", con, if_exists="replace")
airports.to_sql("airports", con, if_exists="replace")
weather.to_sql("weather", con, if_exists="replace")

# Przykładowe zapytania

In [45]:
# wszystko jak leci
sql_result = pd.read_sql_query("SELECT * FROM planes", con)
sql_result

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,3,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
5,5,N105UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
6,6,N107US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
7,7,N108UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
8,8,N109UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
9,9,N110UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
10,10,N11106,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
11,11,N11107,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
12,12,N11109,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
13,13,N11113,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
14,14,N11119,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
15,15,N11121,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
16,16,N11127,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
17,17,N11137,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
18,18,N11140,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
19,19,N11150,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
20,20,N11155,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
21,21,N11164,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
22,22,N11165,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
23,23,N11176,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
24,24,N11181,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
25,25,N11184,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
26,26,N11187,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
27,27,N11189,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
28,28,N11191,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
29,29,N11192,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...,...
3292,3292,N984DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3293,3293,N985AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3294,3294,N985DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3295,3295,N986AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3296,3296,N986DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3297,3297,N987AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3298,3298,N987DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3299,3299,N988AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3300,3300,N988DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3301,3301,N989AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3302,3302,N989DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3303,3303,N990AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3304,3304,N990DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3305,3305,N991AT,NaN,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3306,3306,N991DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3307,3307,N992AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3308,3308,N992DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3309,3309,N993AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3310,3310,N993DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3311,3311,N994AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3312,3312,N994DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3313,3313,N995AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3314,3314,N995DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3315,3315,N996AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3316,3316,N996DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3317,3317,N997AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3318,3318,N997DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3319,3319,N998AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3320,3320,N998DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3321,3321,N999DN,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet

In [46]:
# wszystkie wiersze, ale tylko 2 kolumny
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes", con)
sql_result

     tailnum    year
0     N10156  2004.0
1     N102UW  1998.0
2     N103US  1999.0
3     N104UW  1999.0
4     N10575  2002.0
5     N105UW  1999.0
6     N107US  1999.0
7     N108UW  1999.0
8     N109UW  1999.0
9     N110UW  1999.0
10    N11106  2002.0
11    N11107  2002.0
12    N11109  2002.0
13    N11113  2002.0
14    N11119  2002.0
15    N11121  2003.0
16    N11127  2003.0
17    N11137  2003.0
18    N11140  2003.0
19    N11150  2003.0
20    N11155  2004.0
21    N11164  2004.0
22    N11165  2004.0
23    N11176  2004.0
24    N11181  2005.0
25    N11184  2005.0
26    N11187  2005.0
27    N11189  2005.0
28    N11191  2005.0
29    N11192  2005.0
...      ...     ...
3292  N984DL  1991.0
3293  N985AT  2001.0
3294  N985DL  1991.0
3295  N986AT  2001.0
3296  N986DL  1991.0
3297  N987AT  2001.0
3298  N987DL  1991.0
3299  N988AT  2001.0
3300  N988DL  1991.0
3301  N989AT  2001.0
3302  N989DL  1991.0
3303  N990AT  2001.0
3304  N990DL  1991.0
3305  N991AT     NaN
3306  N991DL  1991.0
3307  N992AT  2002.0
3308  N992DL  1991.0
3309  N993AT  2002.0
3310  N993DL  1991.0
3311  N994AT  2002.0
3312  N994DL  1991.0
3313  N995AT  2002.0
3314  N995DL  1991.0
3315  N996AT  2002.0
3316  N996DL  1991.0
3317  N997AT  2002.0
3318  N997DL  1992.0
3319  N998AT  2002.0
3320  N998DL  1992.0
3321  N999DN  1992.0

[3322 rows x 2 columns]

In [47]:
# niektore wiersze, ale tylko 2 kolumny
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes WHERE year >= 2000", con)
sql_result

     tailnum    year
0     N10156  2004.0
1     N10575  2002.0
2     N11106  2002.0
3     N11107  2002.0
4     N11109  2002.0
5     N11113  2002.0
6     N11119  2002.0
7     N11121  2003.0
8     N11127  2003.0
9     N11137  2003.0
10    N11140  2003.0
11    N11150  2003.0
12    N11155  2004.0
13    N11164  2004.0
14    N11165  2004.0
15    N11176  2004.0
16    N11181  2005.0
17    N11184  2005.0
18    N11187  2005.0
19    N11189  2005.0
20    N11191  2005.0
21    N11192  2005.0
22    N11193  2005.0
23    N11194  2005.0
24    N11199  2006.0
25    N11206  2000.0
26    N11535  2001.0
27    N11536  2001.0
28    N11539  2001.0
29    N11544  2002.0
...      ...     ...
1995  N967WN  2011.0
1996  N968AT  2001.0
1997  N968WN  2011.0
1998  N969AT  2001.0
1999  N969WN  2011.0
2000  N970AT  2001.0
2001  N971AT  2001.0
2002  N972AT  2001.0
2003  N974AT  2002.0
2004  N975AT  2002.0
2005  N977AT  2002.0
2006  N978AT  2002.0
2007  N978SW  2004.0
2008  N979AT  2002.0
2009  N980AT  2002.0
2010  N981AT  2002.0
2011  N982AT  2002.0
2012  N985AT  2001.0
2013  N986AT  2001.0
2014  N987AT  2001.0
2015  N988AT  2001.0
2016  N989AT  2001.0
2017  N990AT  2001.0
2018  N992AT  2002.0
2019  N993AT  2002.0
2020  N994AT  2002.0
2021  N995AT  2002.0
2022  N996AT  2002.0
2023  N997AT  2002.0
2024  N998AT  2002.0

[2025 rows x 2 columns]

In [48]:
# niektore wiersze, ale tylko 2 kolumny, laczenie warunkow
sql_result = pd.read_sql_query("SELECT * FROM planes WHERE year >= 2000 and seats > 100", con)
sql_result

,index,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,34,N11206,2000.0,Fixed wing multi engine,BOEING,737-824,2,149,None,Turbo-fan
1,46,N117UW,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
2,47,N118US,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
3,48,N119US,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
4,70,N121UW,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
5,77,N122US,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
6,78,N123UW,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
7,79,N124US,2000.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,None,Turbo-fan
8,86,N125UW,2009.0,Fixed wing multi engine,AIRBUS,A320-214,2,182,None,Turbo-fan
9,87,N126UW,2009.0,Fixed wing multi engine,AIRBUS,A320-214,2,182,None,Turbo-fan
10,88,N127UW,2010.0,Fixed wing multi engine,AIRBUS,A320-214,2,182,None,Turbo-fan
11,89,N128UW,2010.0,Fixed wing multi engine,AIRBUS,A320-214,2,182,None,Turbo-fan
12,215,N150UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
13,216,N151UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
14,218,N152UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
15,221,N153UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
16,223,N154UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
17,228,N155UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
18,230,N156UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
19,233,N157UW,2013.0,Fixed wing multi engine,AIRBUS,A321-211,2,199,None,Turbo-fan
20,246,N1607B,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
21,247,N1608,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
22,248,N1609,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
23,249,N1610D,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
24,251,N1611B,2000.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
25,252,N1612T,2001.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
26,253,N1613B,2001.0,Fixed wing multi engine,BOEING,767-332,2,330,None,Turbo-fan
27,261,N161UW,2001.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-211,2,199,None,Turbo-jet
28,265,N162UW,2001.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-211,2,199,None,Turbo-jet
29,266,N163US,2001.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A321-211,2,199,None,Turbo-jet
...,...,...,...,...,...,...,...,...,...,...
1284,3139,N941WN,2009.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1285,3143,N942WN,2009.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1286,3148,N943WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1287,3153,N944WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1288,3158,N945WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1289,3162,N946WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1290,3166,N947WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1291,3171,N948WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1292,3175,N949WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1293,3179,N950WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1294,3184,N951WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1295,3189,N952WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1296,3195,N953WN,2010.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1297,3199,N954WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1298,3204,N955WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1299,3210,N956WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1300,3215,N957WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1301,3220,N958WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1302,3225,N959WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1303,3229,N960WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1304,3234,N961WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1305,3237,N962WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1306,3242,N963WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1307,3246,N964WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1308,3249,N965DN,2000.0,Fixed wing multi engine,BOEING,MD-90-30,2,142,None,Turbo-fan
1309,3251,N965WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1310,3254,N966WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1311,3258,N967WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1312,3261,N968WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan
1313,3264,N969WN,2011.0,Fixed wing multi engine,BOEING,737-7H4,2,140,None,Turbo-fan

In [49]:
sql_result = pd.read_sql_query("SELECT tailnum, year FROM planes WHERE year == 2000 or year==2001", con)
sql_result

    tailnum    year
0    N11206  2000.0
1    N11535  2001.0
2    N11536  2001.0
3    N11539  2001.0
4    N117UW  2000.0
5    N118US  2000.0
6    N119US  2000.0
7    N121UW  2000.0
8    N122US  2000.0
9    N123UW  2000.0
10   N124US  2000.0
11   N12540  2001.0
12   N12900  2001.0
13   N12921  2000.0
14   N12922  2000.0
15   N12924  2000.0
16   N12996  2000.0
17   N13538  2001.0
18   N13903  2001.0
19   N13908  2001.0
20   N13913  2001.0
21   N13914  2001.0
22   N13988  2000.0
23   N13989  2000.0
24   N13992  2000.0
25   N13994  2000.0
26   N13995  2000.0
27   N13997  2000.0
28   N14542  2001.0
29   N14902  2001.0
..      ...     ...
498  N937AT  2001.0
499  N950AT  2000.0
500  N951AT  2000.0
501  N952AT  2000.0
502  N953AT  2000.0
503  N954AT  2000.0
504  N955AT  2000.0
505  N956AT  2000.0
506  N957AT  2000.0
507  N958AT  2001.0
508  N959AT  2001.0
509  N960AT  2001.0
510  N961AT  2001.0
511  N963AT  2001.0
512  N964AT  2001.0
513  N965AT  2001.0
514  N965DN  2000.0
515  N966AT  2001.0
516  N967AT  2001.0
517  N968AT  2001.0
518  N969AT  2001.0
519  N970AT  2001.0
520  N971AT  2001.0
521  N972AT  2001.0
522  N985AT  2001.0
523  N986AT  2001.0
524  N987AT  2001.0
525  N988AT  2001.0
526  N989AT  2001.0
527  N990AT  2001.0

[528 rows x 2 columns]

# 1

In [50]:
sql_result = pd.read_sql_query("SELECT DISTINCT engine FROM planes", con)
sql_result

          engine
0      Turbo-fan
1      Turbo-jet
2  Reciprocating
3        4 Cycle
4    Turbo-shaft
5     Turbo-prop

In [54]:
wynik = pd.DataFrame(pd.unique(planes["engine"]))
# wynik
wynik = wynik.rename({0: "engine"}, axis=1)
# wynik.columns = ["engine"]
wynik

          engine
0      Turbo-fan
1      Turbo-jet
2  Reciprocating
3        4 Cycle
4    Turbo-shaft
5     Turbo-prop

In [52]:
pd.__version__

'0.23.4'

In [53]:
planes.engine.unique()

array(['Turbo-fan', 'Turbo-jet', 'Reciprocating', '4 Cycle', 'Turbo-shaft',
       'Turbo-prop'], dtype=object)

In [27]:
wynik = pd.DataFrame({"engine" : planes.engine.unique()})
# wynik.columns = ["engine"]
wynik

          engine
0      Turbo-fan
1      Turbo-jet
2  Reciprocating
3        4 Cycle
4    Turbo-shaft
5     Turbo-prop